### ISSUE TITLE
TODO does not show on sidebar Android Studio

### ISSUE THREAD

**Issue by tyczj** [ciscorucinski/ChroMATERIAL#19]
In the default Android Studio themes when you do a TODO the right side bar with scrollbar shows the blue line/marker that indicates where a TODO is in the code. ChroMaterial does not seem to show this marker, can it be added somehow?

**Comment by ciscorucinski** [comment]
If you open up settings and search for _TODO_, then look under `Inspections`, do you see if the checkbox is checked or not? 

As an addition, before you installed ChroMATERIAL, the scrollbars did show an indicator of hte TODO's location? But after you installed it, you don't see that indicator?

**Comment by tyczj** [comment]
TODO is not checked under the inspection however when I switch to one of the default themes in android studio such as `Dracula` the TODO indicator shows by the scrollbar. When I switch back to ChroMATERIAL that indicator disappears

**Comment by ciscorucinski** [comment]
When you switch back to `Darcula` and check the TODO settings like above, is that setting checked. I know in ChroMATERIAL it is not, but what about in Darcula?

As a quick fix for you, until I update, you can make sure that checkbox is checked in ChroMATERIAL and then those bars will appear. I didn't think my plugin would effect that. It shouldn't but I will look into why it does.

You might have to reload the tab to get them to appear in the scollbar

**Comment by tyczj** [comment]
The TODO is not checked when I switch back to the Dracula theme

**Comment by ciscorucinski** [comment]
@tyczj With the new update, v1.1.1, is this problem still persisting? Or is it gone?

**Comment by tyczj** [comment]
It does appear to put in an indicator now. How do we change the color or it or can we?

**Comment by ciscorucinski** [comment]
Yes, you can modify anythin that I have modified. Nothing is hidden from you.

To modify the indicator, the easiest way to find it is by typing `Error Stripe Mark` in the **Settings** search feature! Look for the related item you want to modify (you can click it in the preview code window if you see it), and modify the color. 

If you want to add or remove an indicator, you can also do that!

![chromaterial_error_stripe_mark-editing](https://cloud.githubusercontent.com/assets/8707125/12595995/6b2c9646-c4c1-11e5-9f7f-729722366f9b.png)

FYI, which indicator and related colors don't you like? I am always open to suggestion. Also, I will close this issue.

**Comment by tyczj** [comment]
awesome thanks! I was just curious cause the TODO's are the same colors as lint warnings and such that I could not tell the difference between them so thats why I asked
