### ISSUE TITLE
can't use on mac os intelliJ IDEA

### ISSUE THREAD

**Issue by BenzHuang** [ciscorucinski/ChroMATERIAL#20]
hi,i'm download on mac os intelliJ IDEA. after restart, not find on preferences->editor->Color & Fonts->scheme.

**Comment by ciscorucinski** [comment]
This is not an issue with my scheme.

It seems like that is the right path to get to the settings dialog (Preference Dialog). 

Try this instead..

Go to <kbd>Help</kbd> >> <kbd>Find Action...</kbd> and search for **Colors & Fonts**

Also, if you know how to **Search Everywhere** in IntelliJ, then you can also try that to find the correct settings page.

Lastly, check the documentation here: https://www.jetbrains.com/idea/help/configuring-colors-and-fonts.html

Note: I don't use Mac osX, so if any of these work, and you can figure out the correct path, then please reply back and let me know

**Comment by BenzHuang** [comment]
thx

**Comment by ciscorucinski** [comment]
@BenzHuang were you able to find the correct path in OSX? I would like to include that in my README if I can. For some reason, I cannot switch to find the OSX shortcuts and paths in the IntelliJ Documentation.

**Comment by BenzHuang** [comment]
@ciscorucinski sorry, i'm can not find the correct path in OSX
