### ISSUE TITLE
Light edition

### ISSUE THREAD

**Issue by alex3305** [ciscorucinski/ChroMATERIAL#21]
Thanks for the great color scheme, but would it be possible to also create a light version of this?

**Comment by ciscorucinski** [comment]
The light version will take a while to do; however, I do want to get that done. 

I have been testing out an update to the current default theme that I want to push soon. Then I plan on working on the Darcula-compatible theme after that. The light theme will come after that.

If you feel like trying to modify the current color scheme to be light, then I will accept pull requests!
