### ISSUE TITLE
[Discussion] Color Scheme issues

### ISSUE THREAD

**Issue by ciscorucinski** [ciscorucinski/ChroMATERIAL#29]
@mallowigi What setup do you have to modify the color schemes? For me, IntelliJ IDEA CE 2017.1.* seems to have issues with `use inherited attributes`, so extending my base color scheme to several other editor backgrounds (darker, palenight, etc...) is near impossible. 

I also tried to use 2017.2 and it doesn't have the  `use inherited attributes` problem but I cannot seem to create a valid JAR file that can be imported into IntelliJ.

What is your setup and have you experienced issues with the color schemes?

**Comment by mallowigi** [comment]
I'm not using inherited attributes at all since they give me different results all the time, instead I'm providing my own color definitions, even though it's a painful job.

**Comment by ciscorucinski** [comment]
@mallowigi Thanks for the quick reply. That is going to be a huge pain if I cannot figure out why I cannot create a valid Jar file in 2017.2

By the way, have you ever encountered an `ERROR - rationStore.ComponentStoreImpl - Cannot read scheme from <color_scheme_path>.xml` error before. My files have the .icls extension.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000452590-IntelliJ-not-able-to-find-icls-files-Renaming-them-to-xml-allows-them-to-be-found-Is-this-good-?page=1#community_comment_115000363350

**Comment by mallowigi** [comment]
Yeah I've heard about that and i'm using xml files as well. I don't use icls anymore, now that we can export schemes

**Comment by ciscorucinski** [comment]
@mallowigi How do you support different IDE's when making a color scheme? I can download all the different IDE's but I can only use them for a limited time. Also, can just importing/exporting the color schemes be good enough to support languages from other IDE's or do I have to copy/paste the xml? What ways do you use that seem to work the best?

**Comment by mallowigi** [comment]
It's simple: I have a perpetual licence for all ide, and i use Toolbox to manage the versions. So I have all of them installed, aside from Resharper and Android Studio.

As for the languages, in the beginning I thought that just using IDEA Ultimate would be enough but I was wrong as each product has sometimes it's own implementation. So yeah for Php, use PhpStorm, Pycharm for Python, Rubymine for Ruby, Clion for C and Datagrip for sql. And of course you will need AppCode and Rider for their own languages.
For the rest of the languages (Erlang, Groovy, Typescript, Twig...) you just have to download the different plugins .

--
Elior Boukhobza

**Comment by ciscorucinski** [comment]
So it will be very difficult for someone that only develops for Android and mostly programs in Android Studio, but has IntelliJ IDEA CE due to developing a plugin. I'm going to download PyCharm CE and see how interoperating with it is going to be. If just importing and exporting of the color schemes will save the PyCharm specific color scheme xml data or if I have to copy and paste it

Again, thanks for the reply.
