### ISSUE TITLE
Change category to "Editor Color Scheme"

### ISSUE THREAD

**Issue by GauthierPLM** [ciscorucinski/ChroMATERIAL#41]
A new plugin category named "Editor Color Scheme" is now available on Plugin repository.
I think it's a better choice than "Formatting" for the plugin and makes more sense.

**Comment by ciscorucinski** [comment]
I agree. I plan on looking to release a new version within the week or 2. When that happens, I will switch over to the new category.

**Comment by ciscorucinski** [comment]
fixed last week
