### ISSUE TITLE
Font Family Screenshot

### ISSUE THREAD

**Issue by richellyitalo** [ciscorucinski/ChroMATERIAL#43]
Please, What's the font in screenshot ?
https://cloud.githubusercontent.com/assets/8707125/12482832/27668d52-c095-11e5-89e9-01bb67e65aba.PNG

**Comment by ciscorucinski** [comment]
I have been using 2 different fonts during the development of this color scheme plugin.

 - [Hack](https://github.com/source-foundry/Hack) with a `line space of 1.1` in IntelliJ IDEA. This was the font used in the screenshot. The letters are taller, so a larger line space felt better. See what suits your style.

 - [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) with a `line space of 1.0`. This is my current font. The letters are not a tall so no additional line space feels good.

**Comment by richellyitalo** [comment]
Nice.
Thanks!
